In [3]:
import pandas as pd
import numpy as np
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

In [4]:
df = pd.read_csv('hepatitis_cleaned2.csv')
df.head(7)

,s.no.,DIE_LIVE,AGE,SEX,STEROID,ANTIVIRAL,FATIGUE,MALAISE,ANOREXIA,LIVER_BIG,...,SPLEEN_PALPABLE,SPIDERS,ASCITES,VARICES,BILIRUBIN,ALK_PHOSPHATE,SGOT,ALBUMIN,PROTIME,HISTOLOGY
0,0,2,30,2,1.000000,2,2.0,2.0,2.0,1.0,...,2.0,2.0,2.0,2.0,1.000000,85.000000,18.00000,4.000000,61.852273,1
1,1,2,50,1,1.000000,2,1.0,2.0,2.0,1.0,...,2.0,2.0,2.0,2.0,0.900000,135.000000,42.00000,3.500000,61.852273,1
2,2,2,78,1,2.000000,2,1.0,2.0,2.0,2.0,...,2.0,2.0,2.0,2.0,0.700000,96.000000,32.00000,4.000000,61.852273,1
3,3,2,31,1,1.506494,1,2.0,2.0,2.0,2.0,...,2.0,2.0,2.0,2.0,0.700000,46.000000,52.00000,4.000000,80.000000,1
4,4,2,34,1,2.000000,2,2.0,2.0,2.0,2.0,...,2.0,2.0,2.0,2.0,1.000000,105.325397,200.00000,4.000000,61.852273,1
5,5,2,34,1,2.000000,2,2.0,2.0,2.0,2.0,...,2.0,2.0,2.0,2.0,0.900000,95.000000,28.00000,4.000000,75.000000,1
6,6,1,51,1,1.000000,2,1.0,2.0,1.0,2.0,...,1.0,1.0,2.0,2.0,1.427517,105.325397,85.89404,3.817266,61.852273,1

In [6]:
x = np.array(df.loc[:,['AGE','SEX','STEROID','ANTIVIRAL','FATIGUE','MALAISE','ANOREXIA','LIVER_BIG','LIVER_FIRM','SPLEEN_PALPABLE','SPIDERS','ASCITES','VARICES','BILIRUBIN','ALK_PHOSPHATE','SGOT','ALBUMIN','PROTIME','HISTOLOGY']])
y = np.array(df['DIE_LIVE'])
#y

In [67]:
X_train, X_test, y_train, y_test = train_test_split(x,y,test_size=0.25,random_state=7)
[r,c] = X_train.shape
y_train = y_train-1
#y_train
#
y_test

array([2, 1, 2, 2, 2, 1, 1, 2, 2, 2, 1, 1, 2, 2, 2, 2, 1, 2, 2, 1, 2, 2,
       1, 2, 2, 2, 1, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [68]:
lr = 0.6 #learning rate
w = np.random.rand(19,2) #initializing weights
D = [0,0]
print('INITIAL WEIGHTS',w)
e =0
epoch = 100
while(e<epoch):
    for i in range(r):
        for j in range(2):
            temp =0
            for k in range(c):
                temp = temp + ((w[k,j]-x[i,k])**2)
            D[j] = temp
            
        if(D[0]<D[1]):
            J=0
        else :
            J=1
        #print('winning unit is',J+1)
        #print('weight updation ...')
        if J==y_train[i]:
            for m in range(c):

                 w[m,J]=w[m,J] + (lr*(x[i,m]-w[m,J]))
        else:
            for m in range(c):
                w[m,J]=w[m,J] - (lr*(x[i,m]-w[m,J]))
        
    e = e+1
    lr = lr*0.5
print('final weights',w)

INITIAL WEIGHTS [[0.35611145 0.25177795]
 [0.32243499 0.1573512 ]
 [0.39199081 0.62833712]
 [0.39279634 0.09784092]
 [0.54680053 0.66823   ]
 [0.73811432 0.70445316]
 [0.05918255 0.63639943]
 [0.56322791 0.45564522]
 [0.54222434 0.52828919]
 [0.24085532 0.74790548]
 [0.20375277 0.43768886]
 [0.67886873 0.76865325]
 [0.7516762  0.73389761]
 [0.27075539 0.52504988]
 [0.04905274 0.67618246]
 [0.48973161 0.76560089]
 [0.68281016 0.95478069]
 [0.27342145 0.92090133]
 [0.92952463 0.24569422]]
final weights [[-106.44536751   42.16877148]
 [  -1.77530627    1.16478016]
 [  -3.98640563    1.42606955]
 [  -4.5831062     1.81303991]
 [  -3.35230502    1.30051321]
 [  -3.16868375    1.50586266]
 [  -5.94958827    1.79701062]
 [  -3.88501849    1.83636985]
 [  -3.97104911    1.5595991 ]
 [  -5.20545661    1.79453651]
 [  -5.35742864    1.65876887]
 [  -3.41135368    1.85955578]
 [  -3.11313427    1.85511303]
 [  -1.65338593    1.28902028]
 [-289.43146095  111.02090287]
 [-134.26033749   80.0431302 ]
 [  -9.65178513    3.81020514]
 [-233.45824757   64.98861478]
 [   0.71133288    1.41885364]]

In [69]:
out = []
[r,c] = X_test.shape
for i in range(r):
        for j in range(2):
            temp =0
            for k in range(c):
                temp = temp + ((w[k,j]-x[i,k])**2)
            D[j] = temp

        if(D[0] < D[1]):
            out.append(1)
        else:
            out.append(2)
print(out)

[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]

In [70]:
print('%d'%(out!=y_test).sum())
print('%.2f'%accuracy_score(out,y_test))

10
0.74

In [71]:
len(out)

39